FROM golang:1.22.0-alpine3.19

RUN addgroup -S mercari && adduser -S trainee -G mercari
# RUN chown -R trainee:mercari /path/to/db

WORKDIR /app

COPY . /app/
RUN mkdir -p /db && chown -R trainee:mercari /db

RUN go mod tidy
CMD go run app/main.go
